### ISSUE TITLE
report filters setting in angular6

### ISSUE THREAD

**Issue by BaymaxGroot** [ramandeep-singh-1983/ngx-powerbi#13]
I'm using your nice wrapper library with angular6, but when I want to know when I using <ngx-powerbi-component> to generate powerbi report , how to set filter base on report !

Here is some code:
 ```typescript
onEmbedded (report: Report): void {
    if (this.initFilter) {
      console.log(1231);
      report.setFilters([
          {
            target: {
                table: '',
                column: ''
            },
            operator: 'In',
            values: ['something']
          }
        ]);
    }
  }
```

**Comment by ramandeep-singh-1983** [comment]
Filtering with this library should work just as it works with the JavaScript library. Are you getting any errors with the above code? Refer https://github.com/Microsoft/PowerBI-JavaScript/wiki/Filters for details.

For filtering and other advanced stuff, i would recommend you to use 'Method 3' in the readme of ngx-powerbi library instead of 'Method 1'

**Comment by ramandeep-singh-1983** [comment]
Closing this due to lack of response.
