### ISSUE TITLE
How to pass filter parameter

### ISSUE THREAD

**Issue by pbi-app-test-2019** [ramandeep-singh-1983/ngx-powerbi#16]
Hello,
Can anybody help me on

How to pass filter parameter in ngx-powerbi?

**Comment by ramandeep-singh-1983** [comment]
Method 1:
1) Refer this link: https://github.com/Microsoft/PowerBI-JavaScript/wiki/Filters
2) Use Method 3 defined in the ngx-powerbi library documentation: https://github.com/ramandeep-singh-1983/ngx-powerbi
3) Get the report object embed() service method: 
`const report: Report = <Report>(this.powerBiService.embed(this.pbiContainerElement, config));`
The embed method returns an 'Embed' object and you need to type cast it to 'Report' object in order to call report level APIs.
4) Call the setFilters method on the report object. Details are given in the Power BI wiki link above.
```
report.setFilters([filter])
  .catch(errors => {
    // Handle error
  });
```

Method 2:
Construct the embed URL like this: You can get the embed URL from Power BI service portal (app.powerbi.com) and then append the filter string (&$filter=):

`https://app.powerbi.com/reportEmbed?reportId=<put-powerbi-report-id-here>&groupId=<put-powerbi-group-id-here>&$filter=Customers/Name%20eq%20%MyCustomer%27&uid=m4v7z
`

**Comment by ramandeep-singh-1983** [comment]
Closing issue due to lack of response.

**Comment by vishakhadamle** [comment]
I used the method 3 in your documentation and called setFilters on it.
The filter was setup using the Basic filter from -  https://github.com/Microsoft/PowerBI-JavaScript/wiki/Filters

But, the filtering does not seem to work. I still see all the data.
The same filter, when used as url params on my PowerBI dashboard works.

**Comment by ramandeep-singh-1983** [comment]
Not sure what the issue is but you might need to use RLS to filter it from the source itself.
